app <- ShinyDriver$new("../../")
app$snapshotInit("add_entry")

app$snapshot()
app$setInputs(`dboes_table-add_dboes` = "click")
app$setInputs(socialmedia = "Twitter", wait_=FALSE, values_=FALSE)
#app$setInputs(`dboes_table-add_dboes-buttonTwitter` = "click", wait_=FALSE, values_=FALSE)
#app$setInputs(`dboes_table-add_dboes-submit` = "click")
app$setInputs(`dboes_table-add_dboes-Kategorie` = "Abgeordnetenhaus von Berlin")
app$setInputs(`dboes_table-add_dboes-Partei` = "AfD", allowInputNoBinding_ = TRUE)
app$setInputs(`dboes_table-add_dboes-Geschlecht` = "", allowInputNoBinding_ = TRUE)
app$setInputs(`dboes_table-add_dboes-Name` = "", allowInputNoBinding_ = TRUE)
app$setInputs(`dboes_table-add_dboes-SM_Twitter_user` = "", allowInputNoBinding_ = TRUE)
app$setInputs(`dboes_table-add_dboes-SM_Twitter_id` = "", allowInputNoBinding_ = TRUE)
app$setInputs(`dboes_table-add_dboes-Wikipedia_URL` = "", allowInputNoBinding_ = TRUE)
app$setInputs(`dboes_table-add_dboes-Name` = "Testname", allowInputNoBinding_ = TRUE)
app$setInputs(`dboes_table-add_dboes-Partei` = "BIW", allowInputNoBinding_ = TRUE)
app$setInputs(`dboes_table-add_dboes-Geschlecht` = "divers", allowInputNoBinding_ = TRUE)
app$setInputs(`dboes_table-add_dboes-SM_Twitter_user` = "Testuser", allowInputNoBinding_ = TRUE)
app$setInputs(`dboes_table-add_dboes-SM_Twitter_id` = "Tes", allowInputNoBinding_ = TRUE)
app$setInputs(`dboes_table-add_dboes-SM_Twitter_id` = "Testid", allowInputNoBinding_ = TRUE)
app$setInputs(`dboes_table-add_dboes-submit` = "click")
app$snapshot()
app$setInputs(`dboes_table-save_dboes` = "click")
app$setInputs(`dboes_table-save_dboes-submit_save` = "click")
#app$setInputs(`dboes_table-save_dboes-submit_save` = "click")
app$snapshot()
